### ISSUE TITLE
Strategy for scalability with multiple peer updates

### ISSUE THREAD

**Issue by piotr-yuxuan** [petterik/lajt#1]
I've been skimming through [`resources/private/notes/initial-idea.md`](https://github.com/petterik/lajt/blob/master/resources/private/notes/initial-idea.md). I've completely possible I've missed something, but what kind of mechanism do you plan to use to support multiple peers updating the same entity? (some are listed [here](http://sites.computer.org/debull/A16mar/p39.pdf))

Anyway, the general idea looks very promising, I'd love to get updates from this project :-)

UPD: err, by the way, do you know about [replikativ/replikativ](https://github.com/replikativ/replikativ)?

**Comment by petterik** [comment]
@piotr-yuxuan I haven't really stated what this library will do yet, but I'm aiming to just make a small plugin for om.next that adds reactive UI updates using datascript. It might eventually grow to become fulcro like (but probably not as ambitious). So FYI multiple peer updates are not of this libraries immediate concern, but I wrote a longer answer at first, so I included them as well.

To the extent I understand the problem of peers updating a single entity, the client has to handle optimistic update conflict resolutions and render the updated entities. The backend will have to some how make sense of the (possibly) simultaneous updates and tell the clients what the updates resulted in.

This library won't do anything for the backend concerns.

For the client concerns it will (eventually) make it easy to do optimistic updates and rollbacks if needed. Most of this work is already done in sulolive: https://github.com/eponai/sulolive/blob/master/src/eponai/client/backend.cljc#L407

The entities updated will be re-rendered wherever they are in the UI, but this library won't care how it gets the data. As this library will (at first) assume datascript is used for the app-state, it'll be easy to merge datomic transactions received from the backend. How the entities are sent from the backend to the client is (for now) outside of the scope of this library. Querying for only what's been changed since the last query was implemented in sulolive: https://github.com/eponai/sulolive/blob/master/src/eponai/server/datomic/query.clj#L286
